name: 'Setup Dependencies'
description: 'Setup common dependencies for contextd workflows'

inputs:
  setup-python:
    description: 'Install Python'
    required: false
    default: 'false'
  python-version:
    description: 'Python version to install'
    required: false
    default: '3.11'
  setup-go:
    description: 'Install Go'
    required: false
    default: 'false'
  go-version:
    description: 'Go version to install'
    required: false
    default: '1.21'
  setup-gh-cli:
    description: 'Install GitHub CLI'
    required: false
    default: 'true'
  setup-node:
    description: 'Install Node.js'
    required: false
    default: 'false'
  node-version:
    description: 'Node.js version to install'
    required: false
    default: '20'
  setup-pre-commit:
    description: 'Install pre-commit hooks framework'
    required: false
    default: 'false'
  use-make:
    description: 'Use make deps instead of individual installs'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Setup dependencies via make
      if: inputs.use-make == 'true'
      shell: bash
      run: |
        echo "ðŸ“¦ Installing dependencies via make..."
        make deps
        echo "âœ… Dependencies installed via make"
    - name: Setup GitHub CLI
      if: inputs.setup-gh-cli == 'true' && inputs.use-make == 'false'
      shell: bash
      run: |
        # Check if gh is already installed
        if command -v gh >/dev/null 2>&1; then
          echo "âœ… GitHub CLI already installed: $(gh --version)"
        else
          echo "ðŸ“¦ Installing GitHub CLI..."
          # Install gh CLI on Linux
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh -y
          echo "âœ… GitHub CLI installed: $(gh --version)"
        fi

    - name: Setup Python
      if: inputs.setup-python == 'true' && inputs.use-make == 'false'
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Setup Go
      if: inputs.setup-go == 'true' && inputs.use-make == 'false'
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        cache: true

    - name: Setup Node.js
      if: inputs.setup-node == 'true' && inputs.use-make == 'false'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Setup pre-commit
      if: inputs.setup-pre-commit == 'true' && inputs.use-make == 'false'
      shell: bash
      run: |
        # Check if pre-commit is already installed
        if command -v pre-commit >/dev/null 2>&1; then
          echo "âœ… pre-commit already installed: $(pre-commit --version)"
        else
          echo "ðŸ“¦ Installing pre-commit..."
          # Ensure Python/pip is available
          if ! command -v pip3 >/dev/null 2>&1 && ! command -v pip >/dev/null 2>&1; then
            echo "Installing Python and pip..."
            sudo apt update
            sudo apt install -y python3 python3-pip
          fi

          # Install pre-commit
          if command -v pip3 >/dev/null 2>&1; then
            pip3 install --user pre-commit
          else
            pip install --user pre-commit
          fi

          # Add to PATH if needed
          export PATH="$HOME/.local/bin:$PATH"

          echo "âœ… pre-commit installed: $(pre-commit --version)"
        fi

        # Install git hooks
        if [ -f ".pre-commit-config.yaml" ]; then
          echo "ðŸ”— Installing pre-commit git hooks..."
          pre-commit install --hook-type pre-commit
          pre-commit install --hook-type commit-msg
          echo "âœ… Pre-commit hooks installed"
        else
          echo "âš ï¸  No .pre-commit-config.yaml found, skipping hook installation"
        fi

    - name: Verify installations
      shell: bash
      run: |
        echo "=== Installed Tools ==="
        if command -v gh >/dev/null 2>&1; then
          echo "âœ… GitHub CLI: $(gh --version | head -1)"
        fi
        if command -v python3 >/dev/null 2>&1; then
          echo "âœ… Python: $(python3 --version)"
        fi
        if command -v go >/dev/null 2>&1; then
          echo "âœ… Go: $(go version)"
        fi
        if command -v node >/dev/null 2>&1; then
          echo "âœ… Node.js: $(node --version)"
          echo "âœ… npm: $(npm --version)"
        fi
        if command -v pre-commit >/dev/null 2>&1; then
          echo "âœ… pre-commit: $(pre-commit --version)"
        fi
