#!/usr/bin/env bash
#
# contextd MCP Server Setup (Docker)
# Configures contextd to run via persistent Docker container
#

set -e

# Configuration
CONTAINER_NAME="contextd-server"
VOLUME_NAME="contextd-data"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

info() { echo -e "${GREEN}[INFO]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1" >&2; exit 1; }

# Check if Docker is available
check_docker() {
    if ! command -v docker &>/dev/null; then
        error "Docker is not installed or not in PATH.

Please install Docker:
  - macOS: https://docs.docker.com/desktop/install/mac-install/
  - Linux: https://docs.docker.com/engine/install/
  - Windows: https://docs.docker.com/desktop/install/windows-install/"
    fi

    if ! docker info &>/dev/null; then
        error "Docker daemon is not running. Please start Docker Desktop or the Docker service."
    fi

    info "Docker is available"
}

# Validate and pull image
pull_image() {
    local tag="${CONTEXTD_VERSION:-latest}"

    # Validate tag format (alphanumeric, dots, hyphens, underscores only)
    if [[ ! "$tag" =~ ^[a-zA-Z0-9._-]+$ ]]; then
        error "Invalid CONTEXTD_VERSION format: $tag (only alphanumeric, dots, hyphens, underscores allowed)"
    fi

    local image="ghcr.io/fyrsmithlabs/contextd:${tag}"

    info "Pulling contextd Docker image: $image"

    if ! docker pull "$image"; then
        error "Failed to pull image: $image

This may happen if:
  - The image tag does not exist
  - Network connectivity issues
  - GitHub Container Registry is temporarily unavailable

Try:
  docker pull ghcr.io/fyrsmithlabs/contextd:latest"
    fi

    info "Image pulled successfully"
    echo "$image"
}

# Start persistent container if not running
start_container() {
    local image="$1"

    # Check if container exists
    if docker ps -a --format '{{.Names}}' | grep -q "^${CONTAINER_NAME}$"; then
        # Container exists, check if running
        if docker ps --format '{{.Names}}' | grep -q "^${CONTAINER_NAME}$"; then
            info "Container '$CONTAINER_NAME' is already running"
        else
            info "Starting existing container '$CONTAINER_NAME'..."
            docker start "$CONTAINER_NAME"
        fi
    else
        # Create and start new container
        info "Creating persistent container '$CONTAINER_NAME'..."

        # Get current user ID for non-root execution
        local user_id
        user_id=$(id -u)
        local group_id
        group_id=$(id -g)

        docker run -d \
            --name "$CONTAINER_NAME" \
            --restart unless-stopped \
            --memory=2g \
            --cpus=2 \
            --user "${user_id}:${group_id}" \
            -v "${VOLUME_NAME}:/data" \
            -v "${HOME}:${HOME}:ro" \
            -w "${HOME}" \
            "$image" \
            tail -f /dev/null

        info "Container created and started"
    fi

    # Verify container is healthy
    if ! docker ps --format '{{.Names}}' | grep -q "^${CONTAINER_NAME}$"; then
        error "Failed to start container '$CONTAINER_NAME'"
    fi
}

# Generate MCP configuration for persistent container
generate_mcp_config() {
    cat <<'EOF'
{
  "contextd": {
    "type": "stdio",
    "command": "docker",
    "args": [
      "exec",
      "-i",
      "-w",
      "${PWD}",
      "contextd-server",
      "contextd",
      "-mcp"
    ],
    "env": {}
  }
}
EOF
}

# Generate wrapper script for ensuring container is running
generate_wrapper_script() {
    local image="$1"
    local wrapper_path="${HOME}/.local/bin/contextd-docker"

    mkdir -p "${HOME}/.local/bin"

    cat > "$wrapper_path" <<WRAPPER
#!/usr/bin/env bash
# contextd-docker: Wrapper to ensure persistent container is running
# Auto-generated by contextd plugin setup

CONTAINER_NAME="contextd-server"
IMAGE="$image"

# Ensure container is running
if ! docker ps --format '{{.Names}}' | grep -q "^\${CONTAINER_NAME}\$"; then
    if docker ps -a --format '{{.Names}}' | grep -q "^\${CONTAINER_NAME}\$"; then
        docker start "\$CONTAINER_NAME" >/dev/null 2>&1
    else
        # Container doesn't exist - user needs to re-run setup
        echo "Error: contextd container not found. Run: /plugin install contextd:docker@fyrsmithlabs/contextd" >&2
        exit 1
    fi
fi

# Execute contextd in container with current working directory
exec docker exec -i -w "\${PWD}" "\$CONTAINER_NAME" contextd -mcp
WRAPPER

    chmod +x "$wrapper_path"
    info "Created wrapper script: $wrapper_path"
    echo "$wrapper_path"
}

# Main
main() {
    echo "========================================"
    echo "  contextd MCP Server Setup (Docker)"
    echo "========================================"
    echo

    # Check Docker
    check_docker

    # Pull image
    local image
    image=$(pull_image)

    # Start persistent container
    start_container "$image"

    # Generate wrapper script
    local wrapper_path
    wrapper_path=$(generate_wrapper_script "$image")

    echo
    echo "========================================"
    echo "  MCP Configuration"
    echo "========================================"
    echo
    echo "Add this to your Claude Code MCP settings:"
    echo
    cat <<EOF
{
  "contextd": {
    "type": "stdio",
    "command": "$wrapper_path",
    "args": [],
    "env": {}
  }
}
EOF
    echo
    echo "========================================"
    echo "  How It Works"
    echo "========================================"
    echo
    echo "1. A persistent container '$CONTAINER_NAME' runs in the background"
    echo "   - Shared across all Claude Code sessions (cross-session memory)"
    echo "   - Auto-restarts on Docker/system restart"
    echo "   - Resource limits: 2GB RAM, 2 CPUs"
    echo
    echo "2. Data persists in Docker volume: $VOLUME_NAME"
    echo "   Backup:  docker run --rm -v ${VOLUME_NAME}:/data -v \$(pwd):/backup alpine tar czf /backup/contextd-backup.tar.gz /data"
    echo "   Restore: docker run --rm -v ${VOLUME_NAME}:/data -v \$(pwd):/backup alpine tar xzf /backup/contextd-backup.tar.gz -C /"
    echo
    echo "3. Your home directory is mounted read-only for repository indexing"
    echo "   contextd can index any repo under \${HOME}"
    echo
    echo "========================================"
    echo "  Container Management"
    echo "========================================"
    echo
    echo "Stop:    docker stop $CONTAINER_NAME"
    echo "Start:   docker start $CONTAINER_NAME"
    echo "Logs:    docker logs $CONTAINER_NAME"
    echo "Remove:  docker rm -f $CONTAINER_NAME"
    echo "Update:  docker pull $image && docker rm -f $CONTAINER_NAME && ./mcp-setup-docker.sh"
    echo
}

# Run if executed directly (not sourced)
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
