# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# Windows-only builds - Mac/Linux users should use Homebrew
version: 2

project_name: contextd

before:
  hooks:
    - go mod tidy

builds:
  # Pure Go builds for Windows (no CGO, uses remote embeddings)
  - id: contextd-windows
    main: ./cmd/contextd
    binary: contextd
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  - id: ctxd-windows
    main: ./cmd/ctxd
    binary: ctxd
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: contextd-windows-archive
    ids:
      - contextd-windows
      - ctxd-windows
    formats:
      - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^feat'
      order: 0
    - title: Bug Fixes
      regexp: '^fix'
      order: 1
    - title: Performance
      regexp: '^perf'
      order: 2
    - title: Others
      order: 999

# Homebrew: Use separate job to update homebrew-tap (source-based formula)
# goreleaser brews section requires binary archives, we only build Windows

# Chocolatey disabled - requires choco CLI on runner
# chocolateys:
#   - name: contextd
#     ids:
#       - contextd-windows-archive
#     skip_publish: true

release:
  github:
    owner: fyrsmithlabs
    name: contextd
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
  footer: |
    ## Installation

    ### Windows
    Download the zip file and extract to a directory in your PATH.

    ### macOS / Linux
    Use Homebrew:
    ```bash
    brew tap fyrsmithlabs/contextd
    brew install contextd
    ```

announce:
  skip: true
