# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: contextd

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: contextd
    main: ./cmd/contextd
    binary: contextd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  - id: ctxd
    main: ./cmd/ctxd
    binary: ctxd
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: contextd-archive
    ids:
      - contextd
      - ctxd
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    files:
      - README.md
      - LICENSE*
      - config.example.yaml

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^feat'
      order: 0
    - title: Bug Fixes
      regexp: '^fix'
      order: 1
    - title: Performance
      regexp: '^perf'
      order: 2
    - title: Others
      order: 999

brews:
  - name: contextd
    ids:
      - contextd-archive
    repository:
      owner: fyrsmithlabs
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/fyrsmithlabs/contextd"
    description: "AI context and reasoning engine for Claude Code"
    license: "MIT"
    install: |
      bin.install "contextd"
      bin.install "ctxd"
    test: |
      system "#{bin}/contextd", "--help"
      system "#{bin}/ctxd", "--help"

release:
  github:
    owner: fyrsmithlabs
    name: contextd
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"

announce:
  skip: true
