name: Bug Report
description: Report a bug or unexpected behavior in contextd
title: "[Bug]: "
labels: ["type:bug", "status:needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below to help us fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Start contextd with '...'
        2. Execute command '...'
        3. See error
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: Describe the expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Describe the actual behavior...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please paste any relevant log output or error messages
      placeholder: Paste logs here...
      render: shell
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component is affected by this bug?
      options:
        - MCP Server
        - API Server
        - Checkpoint System
        - Remediation System
        - Troubleshooting Service
        - Skills Management
        - Vector Database (Qdrant)
        - Authentication
        - Configuration
        - Observability
        - Multi-Tenant
        - Migration Tools
        - Other (please specify in description)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority/Severity
      description: How severe is this bug?
      options:
        - "Critical: Service crash, data loss, security breach"
        - "High: Major feature broken, workaround exists"
        - "Medium: Minor feature broken, inconvenient"
        - "Low: Cosmetic, edge case, minor annoyance"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: contextd Version
      description: What version of contextd are you running? (run `contextd --version`)
      placeholder: v2.0.0
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: What version of Go? (run `go version`)
      placeholder: go1.23.0
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you running?
      options:
        - Linux
        - macOS
        - WSL2
        - Other (please specify in additional context)
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: What version of the operating system?
      placeholder: Ubuntu 22.04, macOS 14.0, etc.
    validations:
      required: false

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Type
      description: How is contextd deployed?
      options:
        - systemd (Linux)
        - launchd (macOS)
        - Docker
        - Manual execution
        - Other (please specify)
    validations:
      required: false

  - type: checkboxes
    id: data-loss
    attributes:
      label: Data Impact
      description: Does this bug affect data?
      options:
        - label: This bug causes data loss
        - label: This bug corrupts existing data
        - label: This bug affects data integrity
        - label: No data impact

  - type: checkboxes
    id: regression
    attributes:
      label: Regression
      description: Is this a regression from a previous version?
      options:
        - label: This worked in a previous version
        - label: If yes, last working version (specify in additional context)

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Is there a workaround for this issue?
      placeholder: Describe any workarounds you've found...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: |
        - Configuration details
        - Environment variables
        - Related issues
        - Screenshots
        - Database size/stats
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have included reproduction steps
          required: true
        - label: I have included relevant logs/error messages
          required: true
        - label: I have specified the contextd version
          required: true
        - label: I am willing to help test a fix
          required: false

  - type: markdown
    attributes:
      value: |
        ---
        **What happens next?**
        1. Maintainers will triage and add appropriate labels
        2. If critical, we'll respond within 24 hours
        3. We may ask for additional information
        4. A regression test will be created before fixing
        5. You'll be notified when a fix is available

        Thank you for helping improve contextd! 🙏
