name: Performance Issue
description: Report a performance problem or optimization opportunity
title: "[Performance]: "
labels: ["type:performance", "status:needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Report a performance issue or suggest a performance optimization.

        **Performance Targets (from roadmap):**
        - Context compression: 60% target
        - MCP tool latency: <2s
        - API response time: <100ms
        - Memory usage: Reasonable for local service

  - type: textarea
    id: description
    attributes:
      label: Performance Issue Description
      description: Describe the performance problem
      placeholder: |
        What operation is slow?
        When does it happen?
        What's the impact?
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component has the performance issue?
      options:
        - MCP Server
        - API Server
        - Checkpoint System (Search/Save)
        - Remediation System (Search/Save)
        - Troubleshooting Service
        - Skills Management
        - Vector Database (Qdrant)
        - Embedding Generation (TEI/OpenAI)
        - Authentication
        - Configuration Loading
        - Background Indexing
        - Database Queries
        - Network Communication
        - Memory Usage
        - CPU Usage
        - Other (please specify)
    validations:
      required: true

  - type: dropdown
    id: operation
    attributes:
      label: Slow Operation
      description: What specific operation is slow?
      options:
        - checkpoint_search
        - checkpoint_save
        - remediation_search
        - remediation_save
        - troubleshoot
        - list_patterns
        - skill_search
        - skill_apply
        - index_repository
        - MCP tool invocation (general)
        - API endpoint response
        - Database query
        - Embedding generation
        - Startup time
        - Other (please specify)
    validations:
      required: true

  - type: textarea
    id: metrics
    attributes:
      label: Performance Metrics
      description: Provide specific performance measurements
      placeholder: |
        **Current Performance:**
        - Operation time: 5 seconds
        - Memory usage: 500MB
        - CPU usage: 80%
        - Database query time: 3 seconds

        **Expected Performance:**
        - Should complete in: <2 seconds
        - Memory usage: <200MB
        - CPU usage: <50%
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: How can we reproduce this performance issue?
      placeholder: |
        1. Start contextd with configuration...
        2. Execute command...
        3. Measure performance with...
        4. Observe slowdown after...
    validations:
      required: true

  - type: input
    id: dataset-size
    attributes:
      label: Dataset Size
      description: How much data is involved?
      placeholder: "10,000 checkpoints, 5GB vector database, etc."
    validations:
      required: false

  - type: textarea
    id: profiling
    attributes:
      label: Profiling Data
      description: Include any profiling data (CPU, memory, traces)
      placeholder: |
        Paste profiling output, flame graphs, or trace data

        ```
        # pprof output, go tool trace, etc.
        ```
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Include logs showing slow operations
      placeholder: |
        Include OpenTelemetry traces, slow query logs, etc.
      render: shell
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Performance Impact
      description: How severe is the performance impact?
      options:
        - "Critical: Service unusable, blocks all workflows"
        - "High: Significantly impacts user experience"
        - "Medium: Noticeable slowdown, usable with patience"
        - "Low: Minor slowdown, barely noticeable"
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: Frequency
      description: How often does this performance issue occur?
      options:
        - "Always: Every time the operation runs"
        - "Usually: Most of the time (>75%)"
        - "Sometimes: Intermittently (25-75%)"
        - "Rarely: Occasionally (<25%)"
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: Configuration Details
      description: Relevant configuration settings
      placeholder: |
        - Vector database size: 1GB
        - Number of collections: 5
        - Embedding backend: TEI/OpenAI
        - Index size: 10,000 vectors
        - Batch size: 100
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: contextd Version
      description: What version are you running?
      placeholder: v2.0.0
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS?
      options:
        - Linux
        - macOS
        - WSL2
        - Other
    validations:
      required: false

  - type: textarea
    id: hardware
    attributes:
      label: Hardware Specifications
      description: CPU, RAM, disk type, etc.
      placeholder: |
        - CPU: 8 cores, 3.2GHz
        - RAM: 16GB
        - Disk: SSD (NVMe)
    validations:
      required: false

  - type: textarea
    id: optimization-ideas
    attributes:
      label: Optimization Ideas
      description: Any ideas for improving performance?
      placeholder: |
        - Could cache X
        - Should parallelize Y
        - Could use index on Z
        - Batch processing for...
    validations:
      required: false

  - type: checkboxes
    id: optimization-type
    attributes:
      label: Optimization Opportunities
      description: What type of optimization might help?
      options:
        - label: Caching (in-memory, disk)
        - label: Indexing (database, vector search)
        - label: Parallelization (concurrent operations)
        - label: Batch processing (group operations)
        - label: Algorithm optimization (better data structures)
        - label: Query optimization (database queries)
        - label: Network optimization (reduce round-trips)
        - label: Memory optimization (reduce allocations)
        - label: Pre-computation (pre-fetch, pre-calculate)
        - label: Lazy loading (defer expensive operations)

  - type: textarea
    id: workaround
    attributes:
      label: Current Workaround
      description: Have you found any workarounds?
      placeholder: Describe any workarounds...
    validations:
      required: false

  - type: textarea
    id: benchmarks
    attributes:
      label: Benchmark Targets
      description: What performance targets should we aim for?
      placeholder: |
        - Operation should complete in <2s (currently 5s)
        - Memory usage should be <200MB (currently 500MB)
        - Should handle 1000 ops/sec (currently 100 ops/sec)
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: |
        - Related performance issues
        - Performance degradation over time
        - Resource usage trends
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have provided specific performance metrics
          required: true
        - label: I have included reproduction steps
          required: true
        - label: I have searched for similar performance issues
          required: true
        - label: I have included configuration/environment details
          required: false
        - label: I can help test performance improvements
          required: false

  - type: markdown
    attributes:
      value: |
        ---
        **What happens next?**
        1. Maintainers will triage and prioritize based on impact
        2. We may request additional profiling data
        3. Performance benchmarks will be established
        4. Optimization will be implemented and tested
        5. Before/after metrics will be documented

        **Performance Monitoring:**
        - OpenTelemetry traces: http://localhost:16686
        - Metrics dashboard: http://localhost:3001
        - Qdrant UI: http://localhost:6333/dashboard

        Thank you for helping make contextd faster! ⚡
