name: Security Vulnerability
description: Report a security vulnerability (PRIVATE - use responsibly)
title: "[Security]: "
labels: ["type:security", "priority:critical", "status:needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Security Vulnerability Report

        **IMPORTANT**: For serious security vulnerabilities, please consider:
        1. Reporting privately via GitHub Security Advisories
        2. Emailing maintainers directly (see SECURITY.md)
        3. Using this template only for lower-severity issues

        We take security seriously. Thank you for responsible disclosure.

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this vulnerability?
      options:
        - "Critical: Remote code execution, data loss, complete system compromise"
        - "High: Privilege escalation, authentication bypass, data exposure"
        - "Medium: Information disclosure, DoS, limited impact"
        - "Low: Minor information leak, theoretical vulnerability"
    validations:
      required: true

  - type: checkboxes
    id: vulnerability-type
    attributes:
      label: Vulnerability Type (CWE Categories)
      description: What type of vulnerability is this?
      options:
        - label: Authentication/Authorization bypass
        - label: Injection (SQL, command, etc.)
        - label: Path traversal / Directory traversal
        - label: Information disclosure
        - label: Denial of Service (DoS)
        - label: Cross-site scripting (XSS) - if web UI exists
        - label: Insecure deserialization
        - label: Insecure cryptography
        - label: Race condition
        - label: Memory corruption
        - label: Privilege escalation
        - label: Filter injection (related to Issue #60)
        - label: Other (specify in description)

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Describe the security vulnerability
      placeholder: |
        What is the vulnerability?
        How does it compromise security?
        What's the potential impact?
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component is vulnerable?
      options:
        - Authentication System
        - Authorization / Access Control
        - API Server
        - MCP Server
        - Unix Socket Communication
        - Token Management
        - Multi-Tenant Isolation
        - Database / Qdrant
        - Input Validation
        - Configuration System
        - File System Operations
        - Network Communication
        - Cryptography
        - Session Management
        - Other (please specify)
    validations:
      required: true

  - type: textarea
    id: attack-scenario
    attributes:
      label: Attack Scenario
      description: Describe how an attacker could exploit this vulnerability
      placeholder: |
        **Attacker Profile:** (local user, remote attacker, authenticated user, etc.)

        **Attack Steps:**
        1. Attacker does X
        2. System responds with Y
        3. Attacker gains access to Z

        **Prerequisites:** What access/knowledge does attacker need?
    validations:
      required: true

  - type: textarea
    id: proof-of-concept
    attributes:
      label: Proof of Concept
      description: Provide PoC code or reproduction steps (if safe to share)
      placeholder: |
        ```bash
        # Example exploit
        curl --unix-socket ~/.config/contextd/api.sock \
          -H "Authorization: Bearer malicious-token" \
          http://localhost/admin/endpoint
        ```

        **Note:** Redact sensitive details if needed
      render: shell
    validations:
      required: false

  - type: textarea
    id: impact
    attributes:
      label: Impact Analysis
      description: What's the potential impact if exploited?
      placeholder: |
        **Confidentiality:** Can attacker access sensitive data?
        **Integrity:** Can attacker modify data?
        **Availability:** Can attacker disrupt service?

        **Affected Users:** Who is impacted?
        **Scope:** Local, remote, authenticated, unauthenticated?
    validations:
      required: true

  - type: textarea
    id: affected-versions
    attributes:
      label: Affected Versions
      description: Which versions are vulnerable?
      placeholder: |
        - v2.0.0: Vulnerable
        - v1.x.x: Vulnerable
        - v0.x.x: Not affected
    validations:
      required: true

  - type: checkboxes
    id: exploitation
    attributes:
      label: Exploitation Complexity
      description: How easy is it to exploit?
      options:
        - label: Easy - No special knowledge required
        - label: Medium - Requires some technical knowledge
        - label: Hard - Requires deep technical expertise
        - label: Very Hard - Requires specific conditions/race windows

  - type: checkboxes
    id: preconditions
    attributes:
      label: Preconditions for Exploitation
      description: What's required to exploit this?
      options:
        - label: Local access required
        - label: Authenticated access required
        - label: Admin privileges required
        - label: Network access required
        - label: Specific configuration required
        - label: No preconditions (any user can exploit)

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: How can this vulnerability be fixed?
      placeholder: |
        - Implement input validation for X
        - Add authentication check for Y
        - Escape user input in Z
        - Use prepared statements for database queries
    validations:
      required: false

  - type: textarea
    id: workaround
    attributes:
      label: Temporary Workaround
      description: Is there a temporary workaround?
      placeholder: |
        Users can mitigate by:
        - Restricting access to X
        - Disabling feature Y
        - Configuring Z
    validations:
      required: false

  - type: checkboxes
    id: related-standards
    attributes:
      label: Security Standards / References
      description: Related security standards or vulnerabilities
      options:
        - label: CWE reference (specify in additional context)
        - label: CVE reference (if publicly disclosed)
        - label: OWASP Top 10 category
        - label: Similar vulnerability in other projects

  - type: textarea
    id: timeline
    attributes:
      label: Disclosure Timeline
      description: Your timeline for public disclosure
      placeholder: |
        - Reported privately: [date]
        - Fix expected by: [date]
        - Public disclosure: [date] (typically 90 days after report)
    validations:
      required: false

  - type: textarea
    id: credit
    attributes:
      label: Credit / Attribution
      description: How would you like to be credited? (optional)
      placeholder: |
        Name: Your Name
        Company/Organization: (if applicable)
        Twitter/GitHub: @username

        Or prefer to remain anonymous
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: |
        - Related security issues
        - Previous vulnerabilities
        - External references
        - Environment details
    validations:
      required: false

  - type: checkboxes
    id: responsible-disclosure
    attributes:
      label: Responsible Disclosure Agreement
      description: Please confirm responsible disclosure practices
      options:
        - label: I will not publicly disclose until a fix is available
          required: true
        - label: I will not exploit this vulnerability maliciously
          required: true
        - label: I have reported this privately if critical (or explain why not)
          required: true
        - label: I understand this may be made public after patching
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        **What happens next?**
        1. **Immediate Response (24h)**: Security team acknowledges receipt
        2. **Assessment (48h)**: Severity confirmed, impact analyzed
        3. **Fix Development**: Patch developed and tested
        4. **Security Advisory**: CVE assigned if applicable
        5. **Coordinated Disclosure**: Fix released, advisory published
        6. **Credit**: Reporter credited in advisory (if desired)

        **Typical Timeline:**
        - Critical: Fix within 7 days
        - High: Fix within 30 days
        - Medium/Low: Fix within 90 days

        **Security Contacts:**
        - GitHub Security Advisories (preferred for critical issues)
        - Email: security@contextd.dev (if configured)
        - Issue tracker (this template, for lower severity)

        Thank you for practicing responsible disclosure! 🔒

        **Reference:** See SECURITY.md for complete security policy
