name: Specification Request
description: Request creation of a specification document for a feature
title: "[Spec]: "
labels: ["type:documentation", "ai:needs-spec", "status:needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Request creation of a specification document for a new feature or significant change.

        **Note**: This will trigger the spec-creation workflow using the spec-writer agent.

  - type: input
    id: feature-name
    attributes:
      label: Feature Name
      description: Short, descriptive name for the feature
      placeholder: pre-fetch-pattern, advanced-caching, etc.
    validations:
      required: true

  - type: textarea
    id: overview
    attributes:
      label: Feature Overview
      description: High-level description of what this feature does
      placeholder: |
        This feature implements...
        It provides...
        It enables...
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this feature needed? What problem does it solve?
      placeholder: |
        Currently, users face...
        This would improve...
        The benefit is...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Primary Component
      description: Which component will this primarily affect?
      options:
        - MCP Server
        - API Server
        - Checkpoint System
        - Remediation System
        - Troubleshooting Service
        - Skills Management
        - Vector Database (Qdrant)
        - Authentication
        - Configuration
        - Observability
        - Multi-Tenant
        - Migration Tools
        - CLI Tool (ctxd)
        - New Component
        - Multiple Components
        - Other (please specify)
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature is?
      options:
        - "Low: Simple enhancement, 1-2 days"
        - "Medium: Moderate feature, 1-2 weeks"
        - "High: Complex feature, 2-4 weeks"
        - "Very High: Major feature, 1-2 months"
        - "Unknown"
    validations:
      required: false

  - type: dropdown
    id: phase
    attributes:
      label: Roadmap Phase
      description: Which roadmap phase does this belong to?
      options:
        - "Phase 1: Foundation (Context Folding, Memory Bank)"
        - "Phase 2: ReasoningBank Core (Pattern Library)"
        - "Phase 3: Tool Orchestration (Workflows)"
        - "Phase 4: Advanced Integration (Cross-project)"
        - "Phase 5: Ecosystem & Scale (Plugins)"
        - "Not aligned with current roadmap"
    validations:
      required: false

  - type: textarea
    id: requirements
    attributes:
      label: Key Requirements
      description: What are the key requirements this spec should address?
      placeholder: |
        - Must support...
        - Should integrate with...
        - Must maintain compatibility with...
        - Performance requirements...
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: What's in scope and out of scope?
      placeholder: |
        **In Scope:**
        - Feature X
        - Integration with Y

        **Out of Scope:**
        - Feature Z (future enhancement)
        - UI components (CLI only for now)
    validations:
      required: false

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: What other features or systems does this depend on?
      placeholder: |
        - Requires feature X to be complete
        - Depends on library Y
        - Integration with Z
    validations:
      required: false

  - type: checkboxes
    id: research-needed
    attributes:
      label: Research Areas
      description: What areas need research for this spec?
      options:
        - label: SDK/Library research needed
        - label: Architecture pattern research needed
        - label: Performance benchmarking needed
        - label: Security analysis needed
        - label: Competitive analysis needed
        - label: User research needed

  - type: textarea
    id: research-sources
    attributes:
      label: Research Sources
      description: Any specific sources, articles, or references to consider?
      placeholder: |
        - https://github.com/example/repo
        - https://docs.example.com/guide
        - Similar feature in tool X
    validations:
      required: false

  - type: checkboxes
    id: spec-sections
    attributes:
      label: Required Spec Sections
      description: Which sections should the spec include?
      options:
        - label: Overview and Motivation
        - label: Requirements and Acceptance Criteria
        - label: Architecture and Design
        - label: API/Interface Design
        - label: Data Model/Schema
        - label: Performance Considerations
        - label: Security Considerations
        - label: Testing Strategy
        - label: Migration/Upgrade Path
        - label: Documentation Plan
        - label: Open Questions

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Spec Acceptance Criteria
      description: How will we know the spec is complete and ready for implementation?
      placeholder: |
        - [ ] All technical details documented
        - [ ] Architecture diagrams included
        - [ ] API contracts defined
        - [ ] Test strategy outlined
        - [ ] Reviewed and approved by team
    validations:
      required: false

  - type: checkboxes
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Will this feature involve breaking changes?
      options:
        - label: API breaking changes expected
        - label: MCP protocol changes expected
        - label: Database schema changes expected
        - label: Configuration format changes expected
        - label: No breaking changes expected

  - type: textarea
    id: constraints
    attributes:
      label: Constraints and Considerations
      description: Any constraints or special considerations?
      placeholder: |
        - Must maintain backward compatibility
        - Performance budget: <100ms latency
        - Memory constraints: <50MB additional
        - Must work with existing multi-tenant architecture
    validations:
      required: false

  - type: textarea
    id: success-metrics
    attributes:
      label: Success Metrics
      description: How will we measure success of this feature?
      placeholder: |
        - 20% reduction in latency
        - 80% test coverage
        - User satisfaction >4/5
        - Zero production incidents in first month
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information for the spec writer?
      placeholder: |
        - Related issues or PRs
        - Previous discussions
        - Design constraints
        - Team preferences
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have provided a clear feature overview
          required: true
        - label: I have described the motivation and problem
          required: true
        - label: I have outlined key requirements
          required: true
        - label: I have searched for existing specs/issues
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        **What happens next?**
        1. This issue will automatically trigger the `spec-creation.yml` workflow
        2. The spec-writer agent will analyze requirements and research
        3. A comprehensive spec will be created in `docs/specs/<feature-name>/SPEC.md`
        4. A PR will be created for spec review
        5. Once approved, the spec can guide implementation

        **Spec Structure:**
        ```
        docs/specs/<feature-name>/
        ├── SPEC.md           # Main specification
        ├── research/         # Research documents
        └── decisions/        # Decision records
        ```

        Thank you for initiating the spec-driven development process! 📝
